### ISSUE TITLE
Shipping address object being returned for PayPal Payments

### ISSUE THREAD

**Issue by rollick** [VictorAvelar/mollie-api-go#108]
From the Mollie changelog February 2020 - Thursday, 20th
> Added shippingAddress to the PayPal payment details.

Fetching a PayPal payment started failing a few days ago because the Payment / Details / ShippingAddress is a string and not an object.

**Comment by VictorAvelar** [comment]
@rollick thanks for reporting the issue, would you like to open a PR for it? or is up for grabs?

**Comment by rollick** [comment]
I can make a PR. Just testing now.
