### ISSUE TITLE
Implement Captures API resource

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#11]
**Description**
Implement the API endpoints related to the captures resource and provide test coverage, as an example you might take a look at #6 

**Additional context**
The API reference for refunds can be found here: https://docs.mollie.com/reference/v2/captures-api/get-capture

**Comment by ducnt114** [comment]
I'm working on this issue

**Comment by ducnt114** [comment]
I'm working on this issue

**Comment by VictorAvelar** [comment]
Will be good if we can have #30 before starting on this one.
