### ISSUE TITLE
Incorrect text for settlement status open.

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#130]
**Describe the bug**
To map valid Settlement statuses a set of constants are defined on settlements.go, the constant that is supposed to label a settlement as "open"  is mapped to the text `string` 

**Location**
See the error on [settlements.go](https://github.com/VictorAvelar/mollie-api-go/blob/master/mollie/settlements.go#L19)

**Expected behavior**
```go
SettlementStatusOpen    = "open"
```

**Issue spotted on**
 - Master: :white_check_mark:
 - v2.9.0: :white_check_mark:

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please assign me this.

**Comment by VictorAvelar** [comment]
Thanks @himanshu007-creator! let me know if you have any question.

**Comment by VictorAvelar** [comment]
As an extra thing, could you please assign the type [SettlementStatus](https://github.com/VictorAvelar/mollie-api-go/blob/master/mollie/settlements.go#L16) to those constants?

Thanks in advance!

**Comment by VictorAvelar** [comment]
Fixed with #131
