### ISSUE TITLE
Payment specific parameters for payment service

### ISSUE THREAD

**Issue by meruiden** [VictorAvelar/mollie-api-go#134]
**Describe the solution you'd like**
Right now it is only available to specify payment specific parameters for orders even though Mollie supports this for payments as well. Right now its impossible to create an ideal payment and specifying the issue at the same time using the Payments service while Mollie does support this. The order implementation does support payment specific parameters but I'd like to use the payment API.

**Describe alternatives you've considered**
Manual requests are the only way to achieve this right now which is not the best way to work with this library.

**Comment by VictorAvelar** [comment]
Hey @meruiden thanks for reporting the issue, just to clarify that I am understanding your problem and also to check that it will be solved in the best way possible.

What it is not possible now will be something like:

```json
// ... other payment values are not present to make it readable.
{
    "method": "ideal",
    "issuer": "ideal_INGBNL2A"
}
```

Right now that request fails because Issuer is not part of the payment struct.

What should happen is that the Payment struct should contain all possible values for issuer specific values labeled as `omitempty` so that it is not intrusive with other requests. Is this correct?

**Comment by meruiden** [comment]
Hi @VictorAvelar , indeed the payment object misses the option to pass payment specific parameters like the issuer field from your example or fields like billingAddress, cardToken and shippingAddress for the creditcard option. You can find all the options for payment specific parameters here [https://docs.mollie.com/reference/v2/payments-api/create-payment#payment-method-specific-parameters](https://docs.mollie.com/reference/v2/payments-api/create-payment#payment-method-specific-parameters)


```What should happen is that the Payment struct should contain all possible values for issuer specific values labeled as omitempty so that it is not intrusive with other requests. Is this correct?```
Yes this is correct, that would fix the issue indeed! 😄

**Comment by VictorAvelar** [comment]
I have no issue with taking it over, however you prefer it works for me
Iterations are not a problem though, if you decide to go for it I will be pleased to support whenever needed. 😄

**Comment by meruiden** [comment]
If you have the time to implement this somewhere today or tomorrow then id prefer to leave this to you, but if that's too soon I will be able to implement and PR this on Monday since that is when I will be needing this feature again😄
