### ISSUE TITLE
Implement Customers API resource

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#14]
**Description**
Implement the API endpoints related to the chargebacks resource and provide test coverage, as an example you might take a look at #6 

**Additional context**
The API reference for refunds can be found here: https://docs.mollie.com/reference/v2/customers-api/get-customer

**Comment by nguyenmv2** [comment]
I will give this a shot. The API reference link returns 404 @VictorAvelar

**Comment by VictorAvelar** [comment]
> I will give this a shot. The API reference link returns 404 @VictorAvelar

I just realize there is no base page for each resource, I will fix it, thanks for pointing it out. 👍
