### ISSUE TITLE
Module found but does not contain package

### ISSUE THREAD

**Issue by andrei-dascalu-mollie** [VictorAvelar/mollie-api-go#147]
**Describe the bug**

This is more of a question as I've tried to create a simple test application with the following code (as per readme)

```
package main

import (
	"log"

	"github.com/VictorAvelar/mollie-api-go/v2"
)

func main() {
	config := mollie.NewConfig(true, mollie.APITokenEnv)
	client, err := mollie.NewClient(nil, config)
	if err != nil {
		log.Fatal(err)
	}
}
```

However, on doing a `go mod tidy` to get the required packages, I get

```
github.com/VictorAvelar/mollie-api-go/v2: module github.com/VictorAvelar/mollie-api-go/v2@latest found (v2.14.0), but does not contain package github.com/VictorAvelar/mollie-api-go/v2
```

I have also tried to manually load via `go get -u github.com/VictorAvelar/mollie-api-go/v2` but no change

**To Reproduce**
1. setup new go application folder with go modules enabled

**Expected behavior**
package imported and ready to load key from environment

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2
 - Browser Chrome
 - Version 92

**Additional context**
go 1.17 + VSCode

**Comment by VictorAvelar** [comment]
Hi @andrei-dascalu-mollie thanks for raising the issue and being so descriptive about the steps to reproduce it. It seems it is an error on my side when writing the README.md

If you check the `examples` folder you will see that the actual required path is:

```golang
// should be
package examples

import (
	"fmt"
	"log"
	"os"

	"github.com/VictorAvelar/mollie-api-go/v2/mollie"
)

// you have

import (
	"log"

	"github.com/VictorAvelar/mollie-api-go/v2" // <- here the mollie path is missing
)

```

The full code for the example is [here](https://github.com/VictorAvelar/mollie-api-go/blob/master/examples/profiles.go).

I will fix the README but if you continue to experience issues please make sure to let me know and I will be happy to assist you further.

**Comment by VictorAvelar** [comment]
Here you have an example app I am/was working on if it helps for reference: https://github.com/VictorAvelar/mollie-cli

**Comment by andrei-dascalu-mollie** [comment]
@VictorAvelar thanks a lot!
