### ISSUE TITLE
Missing metadata parameter in OrderLine

### ISSUE THREAD

**Issue by Lucurious** [VictorAvelar/mollie-api-go#161]
The metadata parameter of the OrderLine struct is still missing.
Fixing this should be as simple as adding:

``Metadata interface{} `json:"metadata,omitempty"` ``

to the OrderLine struct in mollie/orders.go

**Comment by VictorAvelar** [comment]
Do you want to submit a PR? 

I will be happy to review, merge and release asap

**Comment by Lucurious** [comment]
That should be it!
