### ISSUE TITLE
How to paginate

### ISSUE THREAD

**Issue by jld3103** [VictorAvelar/mollie-api-go#178]
Hey, your library is really awesome! Our company has been using it for a while now and it's working perfectly.
I want to list chargebacks and refunds which is clearly possible with this library, but i can't see a way to leverage the pagination.
I couldn't find any example or test or other piece of code that does the pagination.

Is pagination implemented in this library at all? If not, is there a plan to implement it at some point? This is kind of a deal breaker for us right now, but also we can't really implement it right now because of a deadline. If we would have more time, we could surely implement and contribute pagination.

**Comment by jld3103** [comment]
I figured out that the results of the simple list are fine for now, but we still need the pagination at some point.

**Comment by VictorAvelar** [comment]
Hi @jld3103 

You can already achieve pagination with the library. I put this together just to guide you through the implementation process, `PaginationLinks` is a common type so if you design your methods well, you don't need to duplicate a bunch of code.

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/url"

	"github.com/VictorAvelar/mollie-api-go/v3/mollie"
	"github.com/gorilla/schema"
)

var (
	decoder = schema.NewDecoder()
)

type paginationHelper struct {
	Limit int    `schema:"limit"`
	From  string `schema:"from"`
}

func main() {
	m, err := mollie.NewClient(nil, mollie.NewConfig(false, mollie.APITokenEnv))
	if err != nil {
		log.Fatal(err)
	}

	res, p1, err := m.Payments.List(context.TODO(), &mollie.ListPaymentOptions{
		Limit: 10,
	})
	if err != nil {
		log.Println(res.Request.URL.String())
		log.Fatal(err)
	}

	fmt.Printf("total payments %v\n", p1.Count)

	for p1.Links.Next != nil {
		_, p, err := m.Payments.List(context.TODO(), getNextPageValues(p1.Links.Next.Href))
		if err != nil {
			log.Println(res.Request.URL.String())
			log.Fatal(err)
		}

		fmt.Printf("total payments %v \n", p.Count)
		p1 = p
	}

	log.Print("pagination walk completed.")

}

func getNextPageValues(next string) *mollie.ListPaymentOptions {
	u, err := url.Parse(next)
	if err != nil {
		log.Fatal(err)
	}

	params := paginationHelper{}

	if err := decoder.Decode(&params, u.Query()); err != nil {
		log.Fatal(err)
	}

	if params.From == "" {
		log.Fatal("empty from value")
	}

	mpops := &mollie.ListPaymentOptions{
		From: params.From,
	}

	if params.Limit > 0 {
		mpops.Limit = params.Limit
	}

	return mpops
}
```

Thanks for your kind words about the library, feel free to close the issue if your question was solved.

**Comment by jld3103** [comment]
Hey, thanks a lot for your help! The code example was quite useful, although I implemented it in a slightly different way. I think I was mostly confused by missing fields for paginating chargebacks (as that is what I was trying to do). I implemented them here: https://github.com/VictorAvelar/mollie-api-go/pull/180. Would be nice if you could review and merge soon and make a new release :)
