### ISSUE TITLE
Rename testdata declarations from `var` to `const`

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#18]
More than a feature it will be consistent and good to have all the `testdata` variables changes to constants as indeed is the value will not change.

**Describe the solution you'd like**
For all the example responses inside the `testdata` directory, the declaration is changed from variables to constants.

**Additional context**
The relevant files live within this directory: https://github.com/VictorAvelar/mollie-api-go/tree/master/testdata

**Comment by skywalkerluc** [comment]
May I work on this?

**Comment by BH0** [comment]
:: @skywalkerluc  yes you can work on this, Psst: the "find and replace" function of your text-editor/IDE will save you time.
