### ISSUE TITLE
Provide Examples

### ISSUE THREAD

**Issue by MarcoWel** [VictorAvelar/mollie-api-go#249]
**Is your feature request related to a problem? Please describe.**
Thank you for this great repo! It is not really clear how to get started with it though.

**Describe the solution you'd like**
A few code examples / best practices would help a lot.

**Describe alternatives you've considered**
Trying to make it work by browsing the readme and looking at the test code.

**Additional context**
None

**Comment by VictorAvelar** [comment]
What is your use case?, perhaps if you explain what you are aiming to accomplish I can provide you with some direction on how to achieve it. 😄

**Comment by MarcoWel** [comment]
Thank you for the quick reply!

Well, a very basic example would be to get all payments. For this it is neccessary to iterate thorugh all the pagination.
It would mark a nice "Getting Started" example as well.

This is the most straight-forward solution I could come up with. Extracting the next page's "From" payment ID from the URL does not seem like a very clean way to do it though.

```go
func main() {
	// API token gets loaded by API client automatically, so no need to import it here
	//apiKey := os.Getenv("MOLLIE_API_TOKEN")

	// Create a new Mollie API client config
	config := mollie.NewConfig(true, mollie.APITokenEnv)

	// Create a new Mollie API client
	client, err := mollie.NewClient(nil, config)
	if err != nil {
		log.Fatalf("Failed to create Mollie client: %v", err)
	}

	allPayments := []mollie.Payment{}
	fromPaymentId := ""

	for {
		// Retrieve the list of payments
		_, paymentList, err := client.Payments.List(
			context.Background(),
			&mollie.ListPaymentOptions{From: fromPaymentId, Limit: 250}
		)
		if err != nil {
			log.Fatalf("Failed to retrieve payments: %v", err)
		}
		allPayments = append(allPayments, paymentList.Embedded.Payments...)

		// Get first payment ID from next page or break if there is none
		if paymentList.Links.Next == nil {
			break
		}
		fromPaymentId = GetStringInBetween(paymentList.Links.Next.Href, "from=", "&")
		if fromPaymentId == "" {
			break
		}
	}

	// Output the payments in JSON format
	paymentsJSON, err := json.MarshalIndent(allPayments, "", "  ")
	if err != nil {
		log.Fatalf("Failed to marshal payments to JSON: %v", err)
	}
	fmt.Println(string(paymentsJSON))
}

// Based on: https://stackoverflow.com/a/62555190
func GetStringInBetween(str string, start string, end string) (result string) {
	startPos := strings.Index(str, start)
	if startPos == -1 {
		return ""
	}
	newStr := str[startPos+len(start):]
	endPos := strings.Index(newStr, end)
	if endPos == -1 {
		endPos = len(newStr)
	}
	return newStr[:endPos]
}
```

**Comment by VictorAvelar** [comment]
Oh, I get it! I've been checking out a lot of other libraries to see how they handle things. This particular library was mostly inspired by DigitalOcean's API sdks. They do something similar to what you described. But don't worry, I'll try to give you an example of how to get paginated payments using the current version of the library. After that, I'll see if there's a way to make it even better and less troublesome in the future.

Thanks for being patient with me!

**Comment by MarcoWel** [comment]
Example: Getting all invoice IDs for a settlement:
https://github.com/VictorAvelar/mollie-api-go/issues/252#issuecomment-1570617042
