### ISSUE TITLE
Implement Invoices API resource

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#27]
**Description**
Implement the API endpoints related to the invoice resource and provide test coverage, as an example you might take a look at #6 

**Additional context**
The API reference for refunds can be found here: https://docs.mollie.com/reference/v2/invoices-api/get-invoice

**Comment by ducnt114** [comment]
I can work on this issue

**Comment by VictorAvelar** [comment]
Super, let me know if I can be of any help 😄

**Comment by ducnt114** [comment]
Created pull request at #29

**Comment by VictorAvelar** [comment]
Overall is looking good, I dropped some comments on minor changes so that I can merge it 👍
