### ISSUE TITLE
Implement Miscellaneous API resources

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#28]
**Description**
Implement the API endpoints related to the miscellaneous section and provide test coverage, as an example you might take a look at #6 

**Additional context**
The API reference for refunds can be found here: https://docs.mollie.com/reference/v2/wallets-api/request-apple-pay-payment-session

**Comment by vdepatla** [comment]
I am taking this one

**Comment by VictorAvelar** [comment]
Thank you, please feel free to ask any questions you might have during the implementation process.
