### ISSUE TITLE
Payment Api Method is either an Array or String

### ISSUE THREAD

**Issue by borissmidt** [VictorAvelar/mollie-api-go#316]
**Is your feature request related to a problem? Please describe.**
According to the API it should be possible to set multiple payment methods instead of one.
https://docs.mollie.com/reference/v2/payments-api/create-payment

The reason i would like this is because in belguim kbc, bellfius  and bancontact are the most commen. But kbc and belfius are better priced. But other payment methods are not relevant to my usecase.

**Describe the solution you'd like**
A way to set multiple methods as an array or a workaround to set the method field.

**Comment by VictorAvelar** [comment]
Hi @borissmidt. I'm going to have a look and try to come up with an implementation solution for this use case.

**Comment by VictorAvelar** [comment]
After further investigation this is not hard to fix, however it would be a breaking change. I can add it to the library and then you would need to either wait for the 4.0 tag or just use @master as version when pulling your go module. I know this is risky and not ideal but it is the best compromise I can offer. I am expecting to start working in full to release v4 latest by the end of February and ideally earlier.

**Comment by borissmidt** [comment]
Thank you for the fast response,

I can wait and use bancontact only for now and i'm glad it gets fixed in
the next version.

**Comment by VictorAvelar** [comment]
Resolved in #326
