### ISSUE TITLE
`Payment` struct `AmountChargedBack` has wrong json tag

### ISSUE THREAD

**Issue by arifmahmudrana** [VictorAvelar/mollie-api-go#389]
**Describe the bug**
`Payment` struct `AmountChargedBack` has wrong json tag. It should be `amountChargedBack` but it has `amountChargeback` see https://github.com/VictorAvelar/mollie-api-go/blob/master/mollie/payments.go#L225C55-L225C71

**To Reproduce**
1. Pay with a test payment.
2. Make it a chargeback using the change status GUI
3. call a Get Payment using Postman collection
4. also call a `client.Payments.Get`
5. see although there is `amountChargedBack` in Postman response but there is no `AmountChargedBack` in the Payment

**Expected behavior**
Tobe populated with the `amountChargedBack` value in `AmountChargedBack`

**Screenshots**
![image](https://github.com/user-attachments/assets/cedae8e4-fd57-4d5e-9a18-eee45c86a2a8)
![image](https://github.com/user-attachments/assets/8ca15226-6978-4b0e-bd0a-bc67fbac7899)

**Desktop (please complete the following information):**
- OS: MacOS
- Browser Postman and using API

**Additional context**
Also you can take a look at in https://docs.mollie.com/reference/get-payment and https://github.com/mollie/postman-collection/blob/main/Mollie%20v2%20API%20-%20APIKey%20authentication.postman_collection.json I couldn't find any sample response with `amountChargeBack` but I did find some with `amountChargedBack` so it's most probably a typo in code.

**Comment by VictorAvelar** [comment]
Hey @arifmahmudrana , thanks a lot for reporting this error.

Do you want to go ahead and open a PR with a fix, or should I take care of it?

**Comment by arifmahmudrana** [comment]
Okay I going to take care thanks for your prompt response @VictorAvelar
