### ISSUE TITLE
Correct broken URL for signup

### ISSUE THREAD

**Issue by CyrilBaah** [VictorAvelar/mollie-api-go#406]
**Broken URL for Signup**
The link for [Mollie account](https://www.mollie.com/signup) throws a 404 page error

**To Reproduce**

1. Go to 'https://github.com/VictorAvelar/mollie-api-go'
2. On the 'README.md'
3. Click on '[Mollie account](https://www.mollie.com/signup)'

**Expected behavior**
The page is expected to show the signup page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by CyrilBaah** [comment]
Would like to take on this [issue](https://github.com/VictorAvelar/mollie-api-go/issues/406) if it can be assigned to me

**Comment by VictorAvelar** [comment]
Hey Cyril, if you want to take the original issue and solve all the issues related to broken links, then please go ahead and do it. I'll close this issue as it overlaps with that one.

Feel free to ask any question on the original issue if you need guidance or any support.

**Comment by CyrilBaah** [comment]
Yes, would like to work on it
