### ISSUE TITLE
Change Status property type of ErrorResponse struct

### ISSUE THREAD

**Issue by dwikur21** [VictorAvelar/mollie-api-go#43]
**Describe the bug**
The Status property of ErrorResponse struct have the wrong type. It should be an integer not a string, resulting in ErrorResponse object not being formed correctly.

**To Reproduce**
1. Go to orders_test.go
2. Make a breakpoint at https://github.com/VictorAvelar/mollie-api-go/blob/6b85db55a644c3dcb763a39e6858fb50a798ed92/mollie/orders_test.go#L338
3. Run "debug test"
4. Type "errResp" on Debug Console, press Enter

**Expected behavior**
The Status property of ErrorResponse struct should have a value of 422

**Screenshots**
![image](https://user-images.githubusercontent.com/26384044/68181181-0641dd80-ffc9-11e9-92bd-af7830d6403b.png)
The Status should have a value of 422, as in the testdata package:
![image](https://user-images.githubusercontent.com/26384044/68181261-443f0180-ffc9-11e9-8794-4525be3c9f9a.png)

**Desktop:**
 - OS: Windows 8.1
 - Go version go1.12.6 windows/amd64

**Comment by VictorAvelar** [comment]
Hey man sorry for the delay, it's been crazy times at work, how about introducing StatusCode as int instead of replacing the type, I am worried that the functionality might not be even for all errors and the different resources.

**Comment by dwikur21** [comment]
Hey, no problem :smile: 
Actually, it's me who wrote the ErrorResponse struct :stuck_out_tongue_winking_eye:
And I give the wrong type. I thought, it will improve the readability if it follows the response.
You mean replacing Status as string with StatusCode as int?

**Comment by VictorAvelar** [comment]
Ahh now I completely get it, well then I think to align with the native response it should be StatusCode as int and also you can do the change.
