### ISSUE TITLE
Payment is missing subscriptionId

### ISSUE THREAD

**Issue by KamilKulach** [VictorAvelar/mollie-api-go#53]
The payment struct is missing subscriptionId. The subscriptionId is necessary for when you receive a payment id from a webhook.

**Comment by VictorAvelar** [comment]
Thanks for reporting the issue, would you like to submit a PR to fix this?

**Comment by KamilKulach** [comment]
I just finished doing that. #54

**Comment by VictorAvelar** [comment]
Fixed with #54
