### ISSUE TITLE
Fix linting errors - S1039: unnecessary use of fmt.Sprintf (gosimple)

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#63]
**Is your feature request related to a problem? Please describe.**
As a maintainer, I will like to improve the codebase quality by complying to GolangCI linter, therefore some errors reported need to be fixed.

**Describe the solution you'd like**
Fix all errors reported by the linter with the code
```
S1039: unnecessary use of fmt.Sprintf (gosimple)
```
The list can be retrieved from the [latest CI run](https://github.com/VictorAvelar/mollie-api-go/actions?query=workflow%3A%22Linting+with+golangci-lint%22) for the master branch.

If you have any question or need guidance/help, feel free to start a conversation in this issue.

**Describe alternatives you've considered**
No alternatives can be considered.

**Additional context**
If you cannot fix all of them, submit a PR with the partial solution and I will adjust the issue.

**Comment by carantunes** [comment]
Can I do this one?

**Comment by VictorAvelar** [comment]
Sure! just be aware that this issue was prepared for Hacktoberfest 😄. (starting tomorrow) 🥳

**Comment by VictorAvelar** [comment]
Hi @carantunes 😄 , friendly ping to know if you are still interested in taking this one?

**Comment by carantunes** [comment]
Yes, I'll provide a PR this weekend!

**Comment by VictorAvelar** [comment]
Thanks! 🚀

**Comment by Alt-It** [comment]
I had a similar problem with the code:

		fmt.Sprintf("MIME-Version: 1.0"),

Fixes very easily:

		fmt.Sprintf("MIME-Version: %s", "1.0"),


But most likely, if we don't need to insert a variable into the string, we may not use fmt.Sprintf.
