### ISSUE TITLE
Fix linting error - Error return value of `(*encoding/json.Decoder).Decode` is not checked (errcheck)

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#64]
**Is your feature request related to a problem? Please describe.**
As a maintainer, I will like to improve the codebase quality by complying to GolangCI linter, therefore some errors reported need to be fixed.

**Describe the solution you'd like**
Fix the error reported by the linter with the code
```
Error return value of `(*encoding/json.Decoder).Decode` is not checked (errcheck)
```
The error can be retrieved from the [latest CI run](https://github.com/VictorAvelar/mollie-api-go/actions?query=workflow%3A%22Linting+with+golangci-lint%22) for the master branch.

Located at:  `mollie/mollie.go#L223`

If you have any question or need guidance/help, feel free to start a conversation in this issue.

**Describe alternatives you've considered**
No alternatives can be considered.

**Additional context**
Some tests need to be added to ensure that the solution is working.

**Comment by u5surf** [comment]
@VictorAvelar Hi, Can I work on this issue.?

**Comment by VictorAvelar** [comment]
Sure! just be aware that this issue was prepared for Hacktoberfest 😄. (starting tomorrow) 🥳
