### ISSUE TITLE
Investigate deadcode - `requiredCreateParamRefund` is unused (deadcode)

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#65]
**Is your feature request related to a problem? Please describe.**
As a maintainer, I will like to improve the codebase quality by complying to GolangCI linter, therefore some errors reported need to be fixed.

**Describe the solution you'd like**
Investigate the error reported by the linter with the code (fix if required)
```
`requiredCreateParamRefund` is unused (deadcode)
```
The error can be retrieved from the [latest CI run](https://github.com/VictorAvelar/mollie-api-go/actions?query=workflow%3A%22Linting+with+golangci-lint%22) for the master branch.

Located at:  ` mollie/refunds.go#L108 `

If you have any question or need guidance/help, feel free to start a conversation in this issue.

**Describe alternatives you've considered**
No alternatives can be considered.

**Additional context**
Some tests are possibly needed to ensure that the solution is working.

**Comment by carantunes** [comment]
Hey @VictorAvelar! Can I do this one?

**Comment by VictorAvelar** [comment]
Sure! just be aware that this issue was prepared for Hacktoberfest 😄. (starting tomorrow) 🥳 

p.s. Also, I won't like to assign it to you until there is a PR approved for #63
