### ISSUE TITLE
Create code samples for payment methods

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#68]
**Is your feature request related to a problem? Please describe.**
As a maintainer, I will like to offer code samples for the most common mollie workflows, this will make the use of the library easier and also reduce the entry barrier for people new to go.

**Describe the solution you'd like**
Replicate Methods examples provided on [mollie's documentation](https://docs.mollie.com).

Provide examples for:
- [List payment methods](https://docs.mollie.com/reference/v2/methods-api/list-methods)
- [List all payment methods](https://docs.mollie.com/reference/v2/methods-api/list-all-methods)
- [Get payment method](https://docs.mollie.com/reference/v2/methods-api/get-method)

Make sure to also add at least one example test case so that godoc can render it.

**Describe alternatives you've considered**
No other alternatives were considered, but I'm open to suggestions.

**Additional context**
N/A

**Comment by TITANMQ** [comment]
Can I do this one?
