### ISSUE TITLE
Create code samples for customers

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#74]
**Is your feature request related to a problem? Please describe.**
As a maintainer, I will like to offer code samples for the most common mollie workflows, this will make the use of the library easier and also reduce the entry barrier for people new to go.

**Describe the solution you'd like**
Replicate *customers* examples provided on [mollie's documentation](https://docs.mollie.com).

Provide examples for:
- [Create customer](https://docs.mollie.com/reference/v2/customers-api/create-customer)
- [Get customer](https://docs.mollie.com/reference/v2/customers-api/get-customer)
- [Update customer](https://docs.mollie.com/reference/v2/customers-api/update-customer)
- [Delete customer](https://docs.mollie.com/reference/v2/customers-api/delete-customer)
- [List customers](https://docs.mollie.com/reference/v2/customers-api/list-customers)
- [Create customer payment](https://docs.mollie.com/reference/v2/customers-api/create-customer-payment)
- [List customer payments](https://docs.mollie.com/reference/v2/customers-api/list-customer-payments)

Make sure to also add at least one example test case so that godoc can render it.

**Describe alternatives you've considered**
No other alternatives were considered, but I'm open to suggestions.

**Additional context**
N/A

**Comment by nanikjava** [comment]
@VictorAvelar can you assign me this ticket. Thanks

**Comment by nanikjava** [comment]
@VictorAvelar was thinking of creating a single file example with the above mentioned features - create, list customers, etc.

Thoughts ?

**Comment by VictorAvelar** [comment]
That sounds ok, it's what we are doing for profiles and chargebacks

**Comment by nanikjava** [comment]
> That sounds ok, it's what we are doing for profiles and chargebacks

@VictorAvelar PR ready for review.
