### ISSUE TITLE
Create code samples for subscriptions

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#76]
**Is your feature request related to a problem? Please describe.**
As a maintainer, I will like to offer code samples for the most common mollie workflows, this will make the use of the library easier and also reduce the entry barrier for people new to go.

**Describe the solution you'd like**
Replicate *subscriptions* examples provided on [mollie's documentation](https://docs.mollie.com).

Provide examples for:
- [Create subscription](https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription)
- [Get subscription](https://docs.mollie.com/reference/v2/subscriptions-api/get-subscription)
- [Update subscription](https://docs.mollie.com/reference/v2/subscriptions-api/update-subscription)
- [Cancel subscription](https://docs.mollie.com/reference/v2/subscriptions-api/cancel-subscription)
- [List subscriptions](https://docs.mollie.com/reference/v2/subscriptions-api/list-subscriptions)
- [List all subscriptions](https://docs.mollie.com/reference/v2/subscriptions-api/list-all-subscriptions)
- [List subscription payments](https://docs.mollie.com/reference/v2/subscriptions-api/list-subscriptions-payments)

Make sure to also add at least one example test case so that godoc can render it.

**Describe alternatives you've considered**
No other alternatives were considered, but I'm open to suggestions.

**Additional context**
N/A

**Comment by TITANMQ** [comment]
Can I do this one?
