### ISSUE TITLE
Create code samples for profiles

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#77]
**Is your feature request related to a problem? Please describe.**
As a maintainer, I will like to offer code samples for the most common mollie workflows, this will make the use of the library easier and also reduce the entry barrier for people new to go.

**Describe the solution you'd like**
Replicate **profiles** examples provided on [mollie's documentation](https://docs.mollie.com).

Provide examples for:
- [Create profile](https://docs.mollie.com/reference/v2/profiles-api/create-profile)
- [Get profile](https://docs.mollie.com/reference/v2/profiles-api/get-profile)
- [Get current profile](https://docs.mollie.com/reference/v2/profiles-api/get-profile-me)
- [Update profile](https://docs.mollie.com/reference/v2/profiles-api/update-profile)
- [Delete profile](https://docs.mollie.com/reference/v2/profiles-api/delete-profile)
- [Enable payment method for profile](https://docs.mollie.com/reference/v2/profiles-api/enable-method)
- [Disable payment method for profile](https://docs.mollie.com/reference/v2/profiles-api/disable-method)
- [Enable gift card issuer for profile](https://docs.mollie.com/reference/v2/profiles-api/enable-gift-card-issuer)
- [Disable gift card issuer for profile](https://docs.mollie.com/reference/v2/profiles-api/disable-gift-card-issuer)
- [List profiles](https://docs.mollie.com/reference/v2/profiles-api/list-profiles)

Make sure to also add at least one example test case so that godoc can render it.

**Describe alternatives you've considered**
No other alternatives were considered, but I'm open to suggestions.

**Additional context**
N/A

**Comment by TITANMQ** [comment]
Can I work on this task?

**Comment by VictorAvelar** [comment]
Sure! Let me know if you need any support. Thanks 🎉

**Comment by TITANMQ** [comment]
@VictorAvelar Should I make each example a separate file or contain all the profile examples in one file?

**Comment by VictorAvelar** [comment]
@TITANMQ I pushed #79 as an example 😄, I'm also open to a proposal from your side if you think with this one being quite an extensive API we should take a different approach.

**Comment by TITANMQ** [comment]
Great, I'll take a look thanks

**Comment by TITANMQ** [comment]
@VictorAvelar Has the Enable gift card issuer and the Disable gift card issuer been implemented? Because I cannot seem to find it on the Go Docs.

**Comment by VictorAvelar** [comment]
😅 #58 I guess not. 😢

**Comment by VictorAvelar** [comment]
So if you can submit what you can do as of now, then I will open a follow up ticket to be done when #58 is completed.

**Comment by TITANMQ** [comment]
Okay cool
