### ISSUE TITLE
Code samples to enable / disable gift card issuers

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#83]
**Is your feature request related to a problem? Please describe.**
As a maintainer, I will like to offer code samples for the most common mollie workflows, this will make the use of the library easier and also reduce the entry barrier for people new to go.

**Describe the solution you'd like**
Replicate **profiles** examples provided on [mollie's documentation](https://docs.mollie.com).

Provide examples for:
- [Enable gift card issuer for profile](https://docs.mollie.com/reference/v2/profiles-api/enable-gift-card-issuer)
- [Disable gift card issuer for profile](https://docs.mollie.com/reference/v2/profiles-api/disable-gift-card-issuer)

Make sure to also add at least one example test case so that godoc can render it.

**Describe alternatives you've considered**
No other alternatives were considered, but I'm open to suggestions.

**Additional context**
This issue is a follow-up to complete original requirements of #77 which is blocked by #58 
Once #58 is completed this one can be unblocked.

**Comment by TITANMQ** [comment]
Could I do this task once #58 is completed?

**Comment by VictorAvelar** [comment]
Yes, that would be nice, I should be pushing the code tonight.

**Comment by VictorAvelar** [comment]
Ready 😄

**Comment by TITANMQ** [comment]
Great, I'll work on it tomorrow.
