### ISSUE TITLE
Library housekeeping - Go version upgrade

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#85]
**List of changes**
- Bump go.mod min go version required
- Upgrade the list of dependencies
- Ensure unit tests are still working

**Comment by souvikmaji** [comment]
hey can i work on this?

**Comment by VictorAvelar** [comment]
Sure! Thanks

**Comment by souvikmaji** [comment]
@VictorAvelar, I assume, `make test` will run all the unit tests. correct?

**Comment by VictorAvelar** [comment]
Yes sir, and make test will do the same in a docker container
