### ISSUE TITLE
Implement Refunds API resource

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#9]
**Description**
Implement the API endpoints related to the refunds resource and provide test coverage, as an example you might take a look at #6 

**Additional context**
The API reference for refunds can be found here: https://docs.mollie.com/reference/v2/refunds-api/get-refund

**Comment by dwikur21** [comment]
@VictorAvelar Hi, I'm new to golang but I would like to give this a try. Thanks

**Comment by VictorAvelar** [comment]
Sure, please feel free to ask any questions you might have during the implementation process.
